services:
  - type: web
    name: smart-flask-ml-backend
    runtime: python
    region: ohio
    plan: free
    buildCommand: "cd ml_pipeline && pip install -r requirements.txt"
    startCommand: "cd ml_pipeline && gunicorn -w 1 -b 0.0.0.0:$PORT app:app"
